import { Footer } from "@/components/Footer"
import { Header } from "@/components/Header/Header"
import type { Metadata } from "next"
import { Noto_Color_Emoji, Noto_Sans } from "next/font/google"
import "../styles/globals.css"
import "../styles/structure.css"
import "../styles/typography.css"
import "../styles/variables.css"

const notoSans = Noto_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-noto-sans",
})

const notoColorEmoji = Noto_Color_Emoji({
  weight: ["400"],
  variable: "--font-noto-color-emoji",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${notoSans.variable} ${notoColorEmoji.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
